apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    creationTimestamp: "2022-05-21T08:47:22Z"
    generation: 1
    name: letsencrypt-prod
    resourceVersion: "1556694"
    uid: cedc9fc9-5525-490e-bf07-342223b9aeb3
  spec:
    acme:
      email: burakberkkeskin@gmail.com
      preferredChain: ""
      privateKeySecretRef:
        name: letsencrypt-prod-coineus
      server: https://acme-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: nginx
  status:
    acme:
      lastRegisteredEmail: burakberkkeskin@gmail.com
      uri: https://acme-v02.api.letsencrypt.org/acme/acct/553238806
    conditions:
    - lastTransitionTime: "2022-05-21T08:47:24Z"
      message: The ACME account was registered with the ACME server
      observedGeneration: 1
      reason: ACMEAccountRegistered
      status: "True"
      type: Ready
- apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cert-manager.io/v1","kind":"ClusterIssuer","metadata":{"annotations":{},"name":"letsencrypt-staging"},"spec":{"acme":{"email":"burakberkkeskin@gmail.com","privateKeySecretRef":{"name":"letsencrypt-staging"},"server":"https://acme-staging-v02.api.letsencrypt.org/directory","solvers":[{"http01":{"ingress":{"class":"nginx"}}}]}}}
    creationTimestamp: "2022-05-21T08:44:02Z"
    generation: 1
    name: letsencrypt-staging
    resourceVersion: "1555874"
    uid: 03b8c78a-e48c-4029-a8f6-129ca5af33f4
  spec:
    acme:
      email: burakberkkeskin@gmail.com
      preferredChain: ""
      privateKeySecretRef:
        name: letsencrypt-staging
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      solvers:
      - http01:
          ingress:
            class: nginx
  status:
    acme:
      lastRegisteredEmail: burakberkkeskin@gmail.com
      uri: https://acme-staging-v02.api.letsencrypt.org/acme/acct/54817674
    conditions:
    - lastTransitionTime: "2022-05-21T08:44:04Z"
      message: The ACME account was registered with the ACME server
      observedGeneration: 1
      reason: ACMEAccountRegistered
      status: "True"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
