apiVersion: v1
kind: Service
metadata:
  name: coineus-frontend
  labels:
    app: coineus-frontend
spec:
  selector:
    app: coineus-frontend
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80