apiVersion: v1
kind: Service
metadata:
  name: coineus-price-service
  labels:
    app: coineus-price-service
spec:
  selector:
    app: coineus-price-service
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80