apiVersion: v1
kind: Service
metadata:
  name: coineus-server
  labels:
    app: coineus-server
spec:
  selector:
    app: coineus-server
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80