apiVersion: v1
kind: Service
metadata:
  name: coineus-db
  labels:
    app: coineus-db
spec:
  selector:
    app: coineus-db
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432